name: kinasetree
channels:
  - conda-forge
  - bioconda
dependencies:
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.18
  - aiosignal=1.3.2
  - attrs=25.3.0
  - biopython=1.85
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.1.31
  - cachetools=5.5.2
  - cairo=1.18.4
  - certifi=2025.1.31
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.1
  - click=8.1.8
  - contourpy=1.3.2
  - cryptography=44.0.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - decorator=5.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.57.0
  - freetype=2.13.3
  - freetype-py=2.3.0
  - frozenlist=1.5.0
  - fsspec=2025.3.2
  - gcsfs=2025.3.2
  - google-api-core=2.24.2
  - google-auth=2.39.0
  - google-auth-oauthlib=1.2.1
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.1.0
  - google-crc32c=1.7.1
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.70.0
  - greenlet=3.2.0
  - grpcio=1.71.0
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcxx=20.1.3
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.84.0
  - libgrpc=1.71.0
  - libiconv=1.18
  - libintl=0.23.1
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libntlm=1.8
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libpq=17.4
  - libprotobuf=5.29.3
  - librdkit=2025.03.1
  - libre2-11=2024.07.02
  - libsqlite=3.49.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxgboost=3.0.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.3
  - matplotlib-base=3.10.1
  - multidict=6.4.3
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.2.5
  - oauthlib=3.2.2
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.2.3
  - pcre2=10.44
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - polars=1.27.1
  - propcache=0.3.1
  - proto-plus=1.26.1
  - protobuf=5.29.3
  - pthread-stubs=0.4
  - py-xgboost=3.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycairo=1.28.0
  - pycparser=2.22
  - pyjwt=2.10.1
  - pyopenssl=25.0.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.13.3
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyu2f=0.1.5
  - qhull=2020.2
  - rdkit=2025.03.1
  - re2=2024.07.02
  - readline=8.2
  - reportlab=4.3.1
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rlpycairo=0.2.0
  - rsa=4.9.1
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlalchemy=2.0.40
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - urllib3=2.4.0
  - xgboost=3.0.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yarl=1.20.0
  - zstandard=0.23.0
  - zstd=1.5.7
